# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: scottkit 1.5.0 ruby lib

Gem::Specification.new do |s|
  s.name = "scottkit".freeze
  s.version = "1.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Mike Taylor".freeze]
  s.date = "2017-10-22"
  s.description = "ScottKit is a toolkit for compiling, decompiling and playing adventure games in the Scott Adams format.".freeze
  s.email = "mike@miketaylor.org.uk".freeze
  s.executables = ["md5ruby".freeze, "scottkit".freeze]
  s.extra_rdoc_files = [
    "ChangeLog.md",
    "README.md"
  ]
  s.files = [
    ".yardopts",
    "ChangeLog.md",
    "GPL-2.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/md5ruby",
    "bin/scottkit",
    "data/.gitignore",
    "data/adams/.gitignore",
    "data/adams/AdamsGames.zip",
    "data/adams/Makefile",
    "data/crystal/crystal.map",
    "data/crystal/crystal.sck",
    "data/crystal/crystal.solution",
    "data/dan-and-matt/dan-and-matt.sck",
    "data/dan-and-matt/dan-and-matt.solution",
    "data/howarth/.gitignore",
    "data/howarth/Makefile",
    "data/howarth/mysterious.tar.gz",
    "data/nosferatu/.gitignore",
    "data/nosferatu/Makefile",
    "data/nosferatu/README",
    "data/nosferatu/TODO",
    "data/nosferatu/nosferatu.map",
    "data/nosferatu/nosferatu.regression",
    "data/nosferatu/nosferatu.sck",
    "data/nosferatu/nosferatu.sol",
    "data/nosferatu/nosferatu.transcript",
    "data/test/Makefile",
    "data/test/adams/Makefile",
    "data/test/adams/adv01.solution",
    "data/test/adams/adv01.transcript",
    "data/test/adams/adv01.transcript.md5",
    "data/test/adams/adv02.solution",
    "data/test/adams/adv02.transcript",
    "data/test/adams/adv02.transcript.md5",
    "data/test/adams/adv04.solution",
    "data/test/adams/adv04.transcript",
    "data/test/adams/adv04.transcript.md5",
    "data/test/crystal.decompile",
    "data/test/crystal.sao",
    "data/test/crystal.save-file",
    "data/test/crystal.save-script",
    "data/test/crystal.sck",
    "data/test/crystal.solution",
    "data/test/crystal.transcript",
    "data/test/t6.pretty-print",
    "data/test/t6.sck",
    "data/test/t7.sao",
    "data/test/t7.solution",
    "data/test/t7.transcript",
    "data/tutorial/Makefile",
    "data/tutorial/t1.map",
    "data/tutorial/t1.sck",
    "data/tutorial/t2.map",
    "data/tutorial/t2.sck",
    "data/tutorial/t3.map",
    "data/tutorial/t3.sck",
    "data/tutorial/t4.map",
    "data/tutorial/t4.sck",
    "data/tutorial/t5.map",
    "data/tutorial/t5.sck",
    "data/tutorial/t6.sck",
    "data/tutorial/tutorial.md",
    "data/tutorial/tutorial.source.md",
    "lib/scottkit/compile.rb",
    "lib/scottkit/decompile.rb",
    "lib/scottkit/game.rb",
    "lib/scottkit/play.rb",
    "lib/scottkit/withio.rb",
    "manual/reference.md",
    "notes/Definition-saved-game.txt",
    "notes/Definition-scottfree-1.14.txt",
    "notes/Definition.txt",
    "notes/adventureland-maze",
    "notes/continue-action",
    "scottkit.gemspec",
    "test/test_canonicalise.rb",
    "test/test_compile.rb",
    "test/test_decompile.rb",
    "test/test_play.rb",
    "test/test_playadams.rb",
    "test/test_save.rb",
    "test/withio_test.rb"
  ]
  s.homepage = "http://github.com/MikeTaylor/scottkit".freeze
  s.licenses = ["GPL-2.0".freeze]
  s.rubygems_version = "2.6.11".freeze
  s.summary = "Toolkit for Scott Adams-format adventure games".freeze
end

